name: Changelog Updated?

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Changelog Updated
        uses: tj-actions/verify-changed-files@v14
        id: verify-changed-files
        with:
          files: |
            CHANGELOG.md
